export const brands = {
  admiral: "Admiral",
  amana: "Amana",
  arctic_king: "Arctic King",
  ascoli_america: "Ascoli America",
  avanti: "Avanti",
  bosch: "Bosch",
  cafe: "Cafe",
  comfort_aire: "Comfort Aire",
  conservator: "Conservator",
  crosley: "Crosley",
  cuisinart: "Cuisinart",
  danby: "Danby",
  electrolux: "Electrolux",
  estate: "Estate",
  fischer_and_paykel: "Fisher & Paykel",
  fridgidaire: "Fridgidaire",
  fridgidaire_gallery: "Fridgidaire Gallery",
  frigidaire_professional: "Fridgidaire Professional",
  ge: "GE",
  ge_profile: "GE Profile",
  gibson: "Gibson",
  haier: "Haier",
  hisense: "Hisense",
  hotpoint: "Hotpoint",
  inglis: "Inglis",
  insignia: "Insignia",
  jenn_air: "Jenn-Air",
  kenmore: "Kenmore",
  kitchenaid: "Kitchenaid",
  lg: "LG",
  lg_signature: "LG Signature",
  magic_chef: "Magic Chef",
  maytag: "Maytag",
  midea: "Midea",
  mora: "Mora",
  richmond: "Richmond",
  roper: "Roper",
  samsung: "Samsung",
  speed_queen: "Speed Queen",
  tappan: "Tappan",
  vitara: "Vitara",
  winia: "Winia",
  whirlpool: "Whirlpool",
  white_westinghouse: "White-Westinghouse",
};

export const colors = {
  black: "Black",
  black_stainless: "Black Stainless",
  blue: "Blue",
  bronze: "Bronze",
  brown: "Brown",
  champagne: "Champagne",
  cream: "Cream",
  gold: "Gold",
  green: "Green",
  grey: "Grey",
  orange: "Orange",
  other: "Other",
  panel_ready: "Panel Ready",
  purple: "Purple",
  red: "Red",
  silver: "Silver",
  stainless: "Stainless",
  teal: "Teal",
  white: "White",
  white_stainless: "White Stainless",
  wood: "Wood",
  yellow: "Yellow",
};
