"""baseline

Revision ID: 439dfae9eb7e
Revises: 
Create Date: 2026-03-10 09:39:25.362999

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '439dfae9eb7e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('work_order_events')
    op.drop_table('machine_notes')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('email'))

    op.drop_table('users')
    with op.batch_alter_table('machines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('serial'))

    op.drop_table('machines')
    op.drop_table('work_orders')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work_orders',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('machine_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('initiated_on', sa.DATE(), nullable=False),
    sa.Column('initiated_by', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('current_status', mysql.VARCHAR(length=11), nullable=False),
    sa.Column('closed_on', sa.DATE(), nullable=True),
    sa.Column('archived_on', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['initiated_by'], ['users.id'], name='work_orders_ibfk_2'),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], name='work_orders_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('machines',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('brand', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('model', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('serial', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('category', mysql.VARCHAR(length=13), nullable=False),
    sa.Column('form_factor', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('color', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('condition', mysql.VARCHAR(length=16), nullable=False),
    sa.Column('vendor', mysql.VARCHAR(length=15), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('machines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('serial'), ['serial'], unique=True)

    op.create_table('users',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('first_name', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('last_name', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('password_hash', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('role', mysql.VARCHAR(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('email'), ['email'], unique=True)

    op.create_table('machine_notes',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('content', mysql.TEXT(), nullable=False),
    sa.Column('added_on', sa.DATE(), nullable=False),
    sa.Column('technician_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('machine_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], name=op.f('machine_notes_ibfk_2')),
    sa.ForeignKeyConstraint(['technician_id'], ['users.id'], name=op.f('machine_notes_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('work_order_events',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('work_order_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('machine_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('event_type', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('from_status', mysql.VARCHAR(length=11), nullable=True),
    sa.Column('to_status', mysql.VARCHAR(length=11), nullable=True),
    sa.Column('event_date', sa.DATE(), nullable=False),
    sa.Column('technician_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reason', mysql.VARCHAR(length=8), nullable=True),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], name=op.f('work_order_events_ibfk_2')),
    sa.ForeignKeyConstraint(['technician_id'], ['users.id'], name=op.f('work_order_events_ibfk_3')),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], name=op.f('work_order_events_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
